Feature 1080 detail page
Strongminds/kitos pull request #301
Opened 2020-09-07 08:08 UTC by mbkstrongminds

2020-09-10 13:05 UTC, mbkstrongminds commented on Presentation.Web/app/shared/navigation/navigation-sub.view.html
> +        <a data-ui-sref="{{link.state}}" data-ng-class="{'btn-tab-active': $state.includes(link.state) || $state.includes(link.substate) || $state.includes('data-processing.edit-agreement')}">{{link.
Ved ikke om der findes en bedre måde her.
Link.parentState eller noget ala dette.

2020-09-10 13:49 UTC, mbkstrongminds commented on Presentation.Web/app/shared/navigation/navigation-sub.view.html
> +        <a data-ui-sref="{{link.state}}" data-ng-class="{'btn-tab-active': $state.includes(link.state) || $state.includes(link.substate) || $state.includes('data-processing.edit-agreement')}">{{link.
$state.includes('parentState') ser ud til at virke

2020-09-11 06:17 UTC, mrjsawdk requested changes
@mbkstrongminds Review done

Der er et par justeringer, som skal foretages og noget oprydning, som mangler. Brug gerne de værktøjer du har aktivt f.eks. hjælper Re#er rigtig meget med at markere ting du ikke bruger eller ting der ikke behøves at være felter/kan være read-only

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-agreement-edit.controller.ts
> +                _.remove(this.$rootScope.page.subnav.buttons, (o: any) => o.text === "Slet Databehandlingsaftale");
måske bedre hvis du bruger dataElementType. Den er nok mere robust som nøgle end teksten

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-agreement-edit.view.html
> +                <h3>Databehandling</h3>
Nej det er en Databehandleraftale

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-agreement-edit.view.html
> +                    <a data-ui-sref="data-processing.edit-agreement.main"><img src="/Content/img/Systemforside.svg"></img> Databehandlerforside</a>
Rename til "Forside"

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-agreement-modal-create.controller.ts
> +                                // This is handled in Save and saveAndProcess
husk ændringerne fra min branch. Denne dialog er broken nu

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-subnav.controller.ts
> +            private $scope,
Kig din dependency liste igennem. De fleste bruges kun i ctor scope og skal derfor ikke være felter på klassen og f.eks. http bruges slet ikke. Ryd op

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-subnav.controller.ts
> +                        case Models.Api.ApiResponseErrorCategory.Conflict:
Conflict skal ikke være en case her. Det kan "not found" til gengæld så udvid "mapperen" og "kategorien" til at indeholde NotFound og så håndter den her på forskellig vis dvs. notfound = besked1 og alt andet kan du faktisk ikke svare andet på end det der står i din "default"

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-subnav.controller.ts
> +                                msg.toErrorMessage("Fejl! Kunne ikke slatte databehandleraftale, kan allerede være slettet!");
Stavefejl

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-agreement-tab-main.ts
> +        public headerName: string = this.dataProcessingAgreement.name;
fjern public access modifier. Public er default visibility

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-agreement-tab-main.ts
> +            private notify,
Kig denne liste igennem. Nogle dependencies bruges slet ikke og nogle kan sættes til readonly

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-agreement-tab-main.ts
> +            var msg = this.notify.addInfoMessage('Ændre navn på databehandleraftale');
du mangler nutids-r

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-agreement-tab-main.ts
> +            private hasWriteAccess,
den skal nok være public for at det giver mening for læseren af klassen for view tilgår den jo og ja det virker alligevel, men lige nu ligner det bare en ubrugt property. Du kan evt. smide et interface på din controller så det er tydligt at se hvilke dele der udstilles til view som viewModel og så slapper eslint også lidt af

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/services/dataProcessingAgreementService.ts
> +        delete(dataProcessingAgreementId: number): angular.IPromise<IDataProcessingAgreementDeletedResult>;
du mangler en GET her (se tidligere kommentar) og den skal jo så returnere en typestærk version af dba så du skal også lige have defineret sådan en. Det er heldigvis nemt for der er jo kun 2 properties - Id og Name

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/services/dataProcessingAgreementService.ts
> +                            error: "TODO"
TODO?

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/services/dataProcessingAgreementService.ts
> +                        modified: true,
hvilken mening giver den boolean? Den er vel ENTEN modifier eller ERROR (thrown). JEg har også renset "createdResult" i min branch

2020-09-11 06:17 UTC, mrjsawdk commented on Presentation.Web/app/shared/navigation/navigation-sub.view.html
> +        <a data-ui-sref="{{link.state}}" data-ng-class="{'btn-tab-active': $state.includes(link.state) || $state.includes(link.substate) || $state.includes('data-processing.edit-agreement')}">{{link.
Der er jo noget galt hvis DBA modulet er det eneste der har det her problem, så se hvad de andre moduler gør

2020-09-11 06:47 UTC, mbkstrongminds commented on Presentation.Web/Tests/data-processing/tabs/data-processing-agreements.main.e2e.spec.ts
> +                .then(() => pageObjectOverview.waitForKendoGrid())
create er lagt i en helper klasse

2020-09-14 07:05 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-agreement-edit.controller.ts
> +                    dataProcessingAgreement: ['$http', '$stateParams', ($http, $stateParams, dataProcessingAgreement = new Services.DataProcessing.DataProcessingAgreementService($http)) => dataProces
Inject service direkte.. navnet skal matche det den er eksponeret som

2020-09-14 08:52 UTC, mrjsawdk commented on Presentation.Web/app/services/dataProcessingAgreementService.ts
> +    export interface IDataProcessingAgreementGetResult {
Nej den skal da returnere den DTO som du har oprettet

2020-09-14 08:53 UTC, mrjsawdk commented on Presentation.Web/app/services/dataProcessingAgreementService.ts
> +    export interface IDataProcessingAgreementGetResult {
Så det her interface skal væk for du har jo DTOen

2020-09-14 08:54 UTC, mrjsawdk approved these changes
@mbkstrongminds Der var lige et "gammelt" interface der skal væk og erstattes af den DTO du har indført... udover det er der jo kun det med menuen som lige skal afklares

2020-09-14 09:27 UTC, merged