Feature kitosudv 1172 dpr oversight
Strongminds/kitos pull request #318
Opened 2020-09-22 13:14 UTC by mbkstrongminds

2020-09-24 10:20 UTC, mrjsawdk reviewed
@mbkstrongminds Der skal lige justeres lidt inden du går videre men i det store hele peger pilen den rigtige vej

2020-09-24 10:20 UTC, mrjsawdk commented on Core.ApplicationServices/GDPR/DataProcessingRegistrationApplicationService.cs
> +            return UpdateProperties(id, new DataProcessingRegistrationPropertyChanges { OversightIntervalChange = new ChangedValue<YearMonthIntervalOption?>(yearMonthIntervalOption) });
Fjern anvendelse af "UpdateProperties" og foretag blot dine ændringer via WithWriteAccess. Ellers skal du bare rette når JMO går i master her om lidt. Fjern også dine rettelser i DataProcessingRegistrationPropertyChanges

2020-09-24 10:20 UTC, mrjsawdk commented on Core.ApplicationServices/GDPR/DataProcessingRegistrationApplicationService.cs
> +            return UpdateProperties(id, new DataProcessingRegistrationPropertyChanges { OversightIntervalNoteChange = new ChangedValue<string>(note) });
Fjern anvendelse af "UpdateProperties" og foretag blot dine ændringer via WithWriteAccess. Ellers skal du bare rette når JMO går i master her om lidt. Fjern også dine rettelser i DataProcessingRegistrationPropertyChanges

2020-09-24 10:20 UTC, mrjsawdk commented on Core.ApplicationServices/GDPR/DataProcessingRegistrationApplicationService.cs
> +            return UpdateProperties(id, new DataProcessingRegistrationPropertyChanges { OversightIntervalNoteChange = new ChangedValue<string>(note) });
OBS: Null er ikke gyldigt input fra klienten ift. note. Hvis den er null skal du terminere med OperationError

2020-09-24 10:20 UTC, mrjsawdk commented on Core.ApplicationServices/GDPR/IDataProcessingRegistrationApplicationService.cs
> +        Result<DataProcessingRegistration, OperationError> UpdateOversightInterval(int id, YearMonthIntervalOption? yesNoIrrelevantOption);
Den værdi skal ikke være nullable og navngivningen skal være i orden f.eks. oversightInterval... i stedet for det andet rod

2020-09-24 10:20 UTC, mrjsawdk commented on Core.ApplicationServices/Model/GDPR/DataProcessingRegistrationPropertyChanges.cs
> +        public Maybe<ChangedValue<YearMonthIntervalOption?>> OversightIntervalChange { get; set; } = Maybe<ChangedValue<YearMonthIntervalOption?>>.None;
ja her skal ændringerne bare væk jf. de tidligere kommentarer

2020-09-24 10:20 UTC, mrjsawdk commented on Core.DomainModel/Core.DomainModel.csproj
> +    <Compile Include="Shared\YearMonthIntervalOption.cs" />
Det er et ret specifikt udfaldsrum som er knyttet til GDPR DP domænet så den skal ikke være i shared. Den er for specifik. Ind under GDPR med den

2020-09-24 10:20 UTC, mrjsawdk commented on Core.DomainModel/GDPR/Read/DataProcessingRegistrationReadModel.cs
> +        public string OversightIntervalNote { get; set; }
Noten skal ikke være i søgemodellen - se storyen

2020-09-24 10:20 UTC, mrjsawdk commented on Core.DomainModel/Shared/YearMonthIntervalOption.cs
> +        Other = 3
Du mangler "undecided" (blank). Det er en ikke-null værdi som de kan vælge ude foran jf. den snak vi havde med dem tidligere på året

2020-09-24 10:20 UTC, mrjsawdk commented on Core.DomainModel/Shared/YearMonthIntervalOption.cs
> +        public static string TranslateToDanishString(this YearMonthIntervalOption? yearMonthIntervalOption)
Den metode bruger du slet ikke for der hvor du mapper bruger du null propagation

2020-09-24 10:20 UTC, mrjsawdk commented on Core.DomainModel/Shared/YearMonthIntervalOption.cs
> +using System.Text;
Ryd op i usings

2020-09-24 10:20 UTC, mrjsawdk commented on Core.DomainServices/GDPR/DataProcessingRegistrationReadModelUpdate.cs
> +            destination.OversightIntervalNote = source.OversightIntervalNote;
væk!

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +            return _dataProcessingRegistrationApplicationService
du mangler at formattere din kaldekæde som de andre metoder

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +                return BadRequest("Value is not provided");
skriv korrekt parameternavn

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +            [FromBody] SingleValueDTO<YearMonthIntervalOption> yearMonthIntervalOption)
navngivning! (parameteren)

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +            [FromBody] SingleValueDTO<string> yearMonthIntervalOptionNote)
navngivning... wtf? det må være oversightIntervalNote

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +                return BadRequest("Value is not provided");
Brug korrekt parameternavn

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +            return _dataProcessingRegistrationApplicationService
du mangler at formattere din kaldekæde som de andre metoder

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +                OversightIntervalOption = value.OversightInterval,
Navngivning... Fjern "Option"..

2020-09-24 10:20 UTC, mrjsawdk commented on Presentation.Web/Models/GDPR/DataProcessingRegistrationDTO.cs
> +        public YearMonthIntervalOption? OversightIntervalOption { get; set; }
Lav en ny DTO type og brug den. Det er ikke sidste gang vi får en værdi hvortil der er tilknyttet en note. Du kan kalde det nye felt på denne dto for OversightInterval:

her er bud på den nye DTO
 
```
class ValueWithNoteDTO<T> {
   public T Value {get;set;}
   public string Note {get;set;}
}
```

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationReadModelsTest.cs
> +            await DataProcessingRegistrationHelper.SendChangeOversightIntervalOptionNoteRequestAsync(registration.Id,
behøves du ikke når noten udgår af read model

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationsTest.cs
> +            dtos.Select(x => new { x.Id, x.Name }).ToExpectedObject().ShouldMatch(new[]
du har en masse tilføjede linjeskift der forstyrrer billedet ift. dine egentlige rettelser. Samtidig er der ikke noget system i linjeskiftene. Revert dem her så kun dine egne ændringer fremgår.

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationsTest.cs
> +                .ConfigureAwait(false);
enten bruger du configureawait(false) på alle kald eller også på ingen. Der er ikke noget system i det her

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationsTest.cs
> +            Assert.Equal(HttpStatusCode.OK,response.StatusCode);
Du mangler at hente den ud bagefter og se at den rent faktisk er sat på den DTO der sendes retur

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationsTest.cs
> +            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
Du mangler at hente den ud bagefter og se at den rent faktisk er sat på den DTO der sendes retur

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationsTest.cs
> +            var dprDTO = await DataProcessingRegistrationHelper.CreateAsync(TestEnvironment.DefaultOrganizationId, name)
enten bruger du configureawait(false) på alle kald eller også på ingen. Der er ikke noget system i det her

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Tools/DataProcessingRegistrationHelper.cs
> +        public static async Task<HttpResponseMessage> SendChangeOversightIntervalOptionRequestAsync(int id, YearMonthIntervalOption? yearMonthIntervalOption, Cookie optionalLogin = null)
navngivning af parameter

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationsTest.cs
> +            var yearMonthIntervalOption = A<YearMonthIntervalOption>();
navngivning!

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/GDPR/DataProcessingRegistrationApplicationServiceTest.cs
> +        public void Can_Update_OversightInterval_To_Null()
nej det må man ikke sætte den til - se tidligere kommentar, så denne test skal test udgår, når værdien ikke længere er nullable

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/GDPR/DataProcessingRegistrationApplicationServiceTest.cs
> +        public void Update_OversightInterval_Returns_Forbidden()
du mangler NotFound casen

2020-09-24 10:20 UTC, mrjsawdk commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/GDPR/DataProcessingRegistrationApplicationServiceTest.cs
> +        {
du mangler notFound

2020-09-24 10:20 UTC, mrjsawdk commented on Core.DomainModel/GDPR/DataProcessingRegistration.cs
> +        public YearMonthIntervalOption? OversightInterval { get; set; }
Her skal den være null modsat på klientkontrakten, så her skal du bare lade den være nullable. Men vi ønsker ikke at man fra klienten kan sætte null. Ønsker man som bruger at sætte "blank" vil vi bruge "undecided". Derved kan vi ved senere analyse se om brugeren rent faktisk har forholdt sig til værdien eller ej modsat hvis null var ok og vi ikke havde mulighed for at sende "undecided" ind

2020-09-28 07:49 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +                return BadRequest("YearMonthIntervalOption must provided");
det hedder parameteren ikke - brug nameof of string interpolation. Så følges evt. navngivninger ad

2020-09-28 07:49 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +                return BadRequest("Note must be provided");
det hedder parameteren ikke - brug nameof of string interpolation. Så følges evt. navngivninger ad

2020-09-28 07:49 UTC, mrjsawdk commented on Presentation.Web/Models/ValueOptionWithOptionalNoteDTO.cs
> +    public class ValueOptionWithOptionalNoteDTO<T>
rename ValueWithOptionalNoteDTO

2020-09-29 11:10 UTC, JacobMalling requested changes
Der er lige lidt rettelser og navne ændringer

2020-09-29 11:10 UTC, JacobMalling commented on Presentation.Web/app/models/ViewModel/Shared/year-month-undecided-interval.ts
> +            this.options = [
Ret til noget der ligner: https://github.com/Strongminds/kitos/blob/76b38038ac9302f14c340d765f254a0efe4aacb8/Presentation.Web/app/models/ViewModel/Shared/yes-no-undecided.ts#L49

2020-09-29 11:10 UTC, JacobMalling commented on Presentation.Web/app/services/dataProcessingRegistrationService.ts
> +        updateOversightInterval(dataProcessingRegistrationId: number, yesNoIrrelevantId: Models.Api.Shared.YearMonthUndecidedIntervalOption);
oversightInterval ikke yesNoIrrelevantId

2020-09-29 11:10 UTC, JacobMalling commented on Presentation.Web/app/services/dataProcessingRegistrationService.ts
> +        updateOversightInterval(dataProcessingRegistrationId: number, yearMonthUndecidedId: Models.Api.Shared.YearMonthUndecidedIntervalOption) {
oversightInterval ikke yearMonthUndecidedId

2020-09-29 11:10 UTC, JacobMalling commented on Presentation.Web/app/services/dataProcessingRegistrationService.ts
> +        updateOversightIntervalNote(dataProcessingRegistrationId: number, note: string) {
remark ikke note

2020-09-29 11:10 UTC, JacobMalling commented on Presentation.Web/app/services/dataProcessingRegistrationService.ts
> +        updateOversightIntervalNote(dataProcessingRegistrationId: number, note: string);
remark ikke note

2020-09-29 11:10 UTC, JacobMalling commented on Tests.Integration.Presentation.Web/GDPR/DataProcessingRegistrationsTest.cs
> +        public async Task Can_Change_Oversight_Option_Note()
Remark ikke note

2020-09-29 11:10 UTC, JacobMalling commented on Tests.Integration.Presentation.Web/Tools/DataProcessingRegistrationHelper.cs
> +            return await HttpApi.PatchWithCookieAsync(TestEnvironment.CreateUrl($"api/v1/data-processing-registration/{id}/oversight-option-note"), cookie, body);
url ændres til remark

2020-09-29 11:10 UTC, JacobMalling commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/GDPR/DataProcessingRegistrationApplicationServiceTest.cs
> +        public void Can_Update_OversightIntervalNote()
Remark

2020-09-29 11:10 UTC, JacobMalling commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/GDPR/DataProcessingRegistrationApplicationServiceTest.cs
> +            var oversightIntervalNote = A<string>();
Remark

2020-09-29 11:10 UTC, JacobMalling commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/GDPR/DataProcessingRegistrationApplicationServiceTest.cs
> +            var oversightIntervalNote = A<string>();
Remark

2020-09-29 11:10 UTC, JacobMalling commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/GDPR/DataProcessingRegistrationApplicationServiceTest.cs
> +        public void Update_OversightIntervalNote_Returns_Forbidden()
Remark

2020-09-29 13:47 UTC, mbkstrongminds commented on Presentation.Web/app/components/data-processing/tabs/data-processing-registration-tab-oversight.controller.ts
> +            this.oversightIntervalNote = this.dataProcessingRegistration.oversightInterval.note;
IEditTextViewModel

2020-09-30 12:23 UTC, mrjsawdk requested changes
Ikke helt i mål endnu men på vej

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +        [Route("{id}/oversight-option")]
ruten er endnu ikke rettet.. det er oversight-interval

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/DataProcessingRegistrationController.cs
> +        [Route("{id}/oversight-option-remark")]
skal være oversight-interval

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/Tests/data-processing/tabs/data-processing-registration.oversight.e2e.spec.ts
> +                .then(() => verifyOversightIntervalNote(intervalRemark));
remark

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/Tests/data-processing/tabs/data-processing-registration.oversight.e2e.spec.ts
> +    function verifyOversightIntervalNote(expectedValue: string) {
remark

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-registration-tab-oversight.view.html
> +                    <label for="oversightIntervalRemark" class="control-label small">Tilsynsinterval bemærkning</label>
Hvorfor er teksten stadig ikke ændret til "Bemærkninger"?

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-registration-tab-oversight.view.html
> +                <!-- Tilsyn Interval Bemærkning -->
engelsk

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/models/ViewModel/Generic/EditTextViewModel.ts
> +            this.currentText = currentText;
Det er fint at du har en ctor men når du nu har det hvorfor tjekker du så ikke invarianterne?
NewTextAdded må vel ikke være null

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/models/ViewModel/Generic/EditTextViewModel.ts
> +    export type NewTextAdded = (newText: string) => void;
Det er vel TextChanged. Added indikerer en tilføjelse men dette handler jo om totalen

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/models/ViewModel/Shared/year-month-undecided-interval.ts
> +            const select2BlankOptionTextValue = "\u200B";
den er allerede trukket ud i en fælles konstant i master. Brug den

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/shared/remarkField/remarkField.view.html
> +          rows="2"
lav rows til en scope parameter også ligesom elementtype

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/shared/remarkField/remarkField.view.html
> +          data-element-field=""
hvad skal du bruge det tomme felt til?

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/shared/remarkField/remarkField.directive.ts
> +                appendurl: "@",
hvad brugerdu appendurl til?... copy paste?

2020-09-30 12:23 UTC, mrjsawdk commented on Presentation.Web/app/shared/remarkField/remarkField.directive.ts
> +                elementType: "=dataElementType"
hvad bruger du den til?... du renderer den ikke og vil du overhovedet det?.. den vil i så fald blive duplikeret i din markup - både det ydre element og din rendering vil få den

2020-09-30 13:12 UTC, mbkstrongminds commented on Presentation.Web/app/components/data-processing/data-processing-registration-overview.controller.ts
> +                            .withStandardWidth(100)
Jeg havde kigget på en bredde og ikke på drop down menuen.
Bliver rettet

2020-09-30 13:39 UTC, mbkstrongminds commented on Presentation.Web/app/components/data-processing/data-processing-registration-overview.controller.ts
> +                            .withStandardWidth(100)
Problem ved "sammentrækning" af kendogrid.
Viser til næste daily.

2020-09-30 13:47 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/data-processing-registration-overview.controller.ts
> +                            .withStandardWidth(100)
Ok den følger vi op på i morgen og lader den være unresolved indtil da

2020-10-01 07:21 UTC, JacobMalling approved these changes
Der har lige sneget sig lidt "note" ind nogle stedet. De skal lige rettes til også. Og så skal du lige have merged med master. Ellers ser det fint ud

2020-10-01 07:21 UTC, JacobMalling commented on Presentation.Web/Tests/data-processing/tabs/data-processing-registration.oversight.e2e.spec.ts
> +        console.log(`Expecting oversight interval note to be set to: ${expectedValue}`);
Remark

2020-10-01 07:21 UTC, JacobMalling commented on Presentation.Web/app/services/dataProcessingRegistrationService.ts
> +        updateOversightIntervalRemark(dataProcessingRegistrationId: number, note: string);
Remark

2020-10-01 07:21 UTC, JacobMalling commented on Presentation.Web/app/services/dataProcessingRegistrationService.ts
> +        updateOversightIntervalRemark(dataProcessingRegistrationId: number, note: string) {
Remark

2020-10-01 07:21 UTC, JacobMalling commented on Infrastructure.DataAccess/Infrastructure.DataAccess.csproj
> +    <Compile Include="Migrations\202009300908424_Added_Agreement_Oversight_Interval_Option_And_Note.cs" />
Den hedder også note her. Det skulle gerne være Remark i stedet. Sørg for at lave den navne ændring når du merger master ind og alligevel skal have lavet ny migration

2020-10-01 07:21 UTC, JacobMalling commented on Presentation.Web/Tests/data-processing/tabs/data-processing-registration.oversight.e2e.spec.ts
> +            var dropdownInterval = "Hver andet år";
Ret til const i stedet for var

2020-10-01 11:50 UTC, mrjsawdk approved these changes

2020-10-01 11:50 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-registration-tab-oversight.view.html
> +                    <label for="oversightIntervalRemark" class="control-label small">Tilsynsinterval Bemærkninger</label>
Hvorfor har du resolved den gamle? Der står stadig noget andet end aftalt

2020-10-01 11:50 UTC, mrjsawdk commented on Presentation.Web/app/models/ViewModel/Generic/EditTextViewModel.ts
> +            if (newText == null) {
brug korrekt ===

2020-10-01 12:43 UTC, merged