WIP: Feature/kitosudv 1313
Strongminds/kitos pull request #472
Opened 2021-05-18 13:30 UTC by mbkstrongminds

2021-05-19 11:39 UTC, JacobMalling requested changes

2021-05-19 11:39 UTC, JacobMalling commented on Tests.Integration.Presentation.Web/Tests.Integration.Presentation.Web.csproj
> +  <ItemGroup />
Den her ændring ser da ikke helt korrekt ud?

2021-05-19 11:39 UTC, JacobMalling commented on Tests.Integration.Presentation.Web/Advice/AdviceTest.cs
> +        public async Task Cannot_Add_Repeatable_Advice_With_StartDate_Before_Today()
Hvad med den situation hvor der ikke er nogen "StartDate"?

2021-05-19 11:39 UTC, JacobMalling commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
> +                        if (dateString2Date($scope.startDate) < $scope.curDate) {
Har du set på hvad "moment" modulet er for noget? Det kunne muligvis benyttes til nogle ting her. Se evt. de ændringer jeg har i https://github.com/Strongminds/kitos/pull/474

2021-05-19 11:39 UTC, JacobMalling commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
> +                        return new Date().toLocaleDateString('en-GB');
Her kan "moment" så nok bruges

2021-05-19 11:39 UTC, JacobMalling commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
> +                            return new Date(dt[0] + "/" + dt[1] + "/" + dt[2].substring(0, 2)).toLocaleDateString(
Måske vi kan bruge moment her? Der kan så bruges bestemt format når det skal sendes til backend

2021-05-20 10:25 UTC, JacobMalling approved these changes
Nogle få rettelser. Når det er rettet og den går grøn merger du bare

2021-05-20 10:25 UTC, JacobMalling commented on Presentation.Web/Controllers/OData/AdviceController.cs
> +
Hvorfor er denne tom?

2021-05-20 10:25 UTC, JacobMalling commented on Presentation.Web/Tests/Helpers/AdviceHelper.ts
> +        //    .then(() => browser.switchTo().alert().accept());
Grøn kode

2021-05-20 10:25 UTC, JacobMalling commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
>                      $scope.showRoleFields = true;
Kan vi ikke også fjerne denne nu vi er i gang? Eller bliver denne stadig brugt?

2021-05-20 10:25 UTC, JacobMalling commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
> +                            payload.StopDate = moment($scope.stopDate + ' 23:59:59', allowedDateFormats, true).format(payloadDateFormat);
Tilføj gerne en kommentar her hvorfor det er vi smider " 23:59:59" på tiden

2021-05-20 10:25 UTC, JacobMalling commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
> +                    function getCurrentDate() {
Bruges denne?

2021-05-20 10:25 UTC, JacobMalling commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
> +                    function formatDate(dateToFormat) {
bruges denne?

2021-05-20 10:25 UTC, JacobMalling commented on Tests.Integration.Presentation.Web/Advice/AdviceTest.cs
> +        private DateTime getRandomDate()
Det er jo ikke helt randomDate. Det er getRandomDateAfterToday()

2021-05-21 11:05 UTC, mrjsawdk commented on Presentation.Web/app/components/it-advice/it-advice-modal-view.html
> +                    <label for="adviceType" class="control-label small">Afsendelsestype <span class="text-danger">*</span></label>
obs: De to der skal matche. Du har lige ændret det så den peger på ingenting :-)
![image](https://user-images.githubusercontent.com/13116889/119127886-2f07b780-ba35-11eb-990f-8abea0517777.png)

2021-05-21 11:31 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Tools/AdviceHelper.cs
> +            var test = body;
hvilken funktion har variablen "test"? Skal den ikke bare ud med skraldet ?

2021-05-21 11:37 UTC, mbkstrongminds commented on Tests.Integration.Presentation.Web/Tools/AdviceHelper.cs
> +            var test = body;
Det har du helt ret i :)

2021-05-21 12:19 UTC, mrjsawdk commented on Presentation.Web/app/components/it-advice/it-advice-modal-dialog.ts
> +                            patchAdviceUserRelation(id, payload);
OBS: Du har lige reverted det kode der fixede 500 fejlen og nukede alle recipients :-)

2021-05-21 12:25 UTC, mrjsawdk requested changes
Vi skal have styr på historikken igen :-)

2021-05-21 12:27 UTC, mrjsawdk commented
det var det her commit der lavede ballade :-) https://github.com/Strongminds/kitos/pull/472/commits/b721d0a994a2840264d79746e193f1c87435dd79

2021-05-21 13:34 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Advice/AdviceTest.cs
> +            return DateTime.Now.AddDays(A<int>());
@mbkstrongminds Bær OBS på at A<int> returnerer også negative tal. For at gøre din test stabil bør du måske ændre den til `Math.Abs(A<int>)`

2021-05-21 14:32 UTC, merged