Feature/KITOSUDV-3193
Strongminds/kitos pull request #781
Opened 2022-09-07 07:41 UTC by a-naskret

## KITOS Pull request template
The following procedure dictates the steps needed before a Pull request can be merged into master.

- [ ] **Implement**: 
      *All requirements are implemented and unit tests are green*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*
      
- [ ] **Request review**: 
      *Tag whomever you wish to review your code*
      
- [ ] **Review completed**: 
      *Reviewer ticks this box when review comments have been submitted*
      
- [ ] **Changes**: 
      *PR owner and reviewer agrees on which changes must be made and the changes are committed.*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*

2022-09-07 09:54 UTC, mrjsawdk requested changes

2022-09-07 09:54 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-registration-tab-main.view.html
> +                               value="{{vm.lastChangedAt}}"
use :: since you don't update this.. removes the two way binding

2022-09-07 09:54 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-registration-tab-main.view.html
> +                               value="{{vm.lastChangedBy}}"
use :: since you don't update this.. removes the two way binding

2022-09-07 09:54 UTC, mrjsawdk commented on Presentation.Web/app/components/data-processing/tabs/data-processing-registration-tab-main.view.html
> +                    </div>
Think you need to work more on your QA skills
![image](https://user-images.githubusercontent.com/13116889/188849334-5160e368-504b-4b4d-8b5e-04a1f95825db.png)
The screenshot is from the default DPA that comes with the clean db.
You placed the markup inside a group which is guarded by a condition

2022-09-09 06:53 UTC, a-naskret commented
@mrjsawdk PR ready for the 2nd review

2022-09-09 08:22 UTC, mrjsawdk requested changes
@a-naskret Still a qa issue here
![image](https://user-images.githubusercontent.com/13116889/189305874-59a3a707-547e-4457-9b86-a05348fa30e9.png)

2022-09-12 06:39 UTC, a-naskret commented
@mrjsawdk ready again

2022-09-12 06:51 UTC, mrjsawdk approved these changes

2022-09-12 06:51 UTC, merged