Feature/KITOSUDV-3422
Strongminds/kitos pull request #817
Opened 2022-10-03 13:29 UTC by a-naskret

## KITOS Pull request template
The following procedure dictates the steps needed before a Pull request can be merged into master.

- [ ] **Implement**: 
      *All requirements are implemented and unit tests are green*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*
      
- [ ] **Request review**: 
      *Tag whomever you wish to review your code*
      
- [ ] **Review completed**: 
      *Reviewer ticks this box when review comments have been submitted*
      
- [ ] **Changes**: 
      *PR owner and reviewer agrees on which changes must be made and the changes are committed.*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*

2022-10-04 12:42 UTC, a-naskret commented
Depends on https://github.com/Strongminds/kitos/pull/812, after 3421 is merged this one is ready for review

2022-10-05 12:28 UTC, a-naskret commented
@mrjsawdk ready

2022-10-06 07:11 UTC, mrjsawdk commented on Infrastructure.DataAccess/Migrations/SQLScripts/Migrate_Users_Not_Associated_With_Any_Org.sql
> +		IsGlobalAdmin = 0,
Procudure..
- select a user which you expect and not expect to be deleted.
- run the migration
- validate that only the expected side effects happen

2022-10-06 10:39 UTC, mrjsawdk requested changes

2022-10-06 10:39 UTC, mrjsawdk commented on Infrastructure.DataAccess/Migrations/SQLScripts/Migrate_Users_Not_Associated_With_Any_Org.sql
> +		Email = CONVERT(NVARCHAR(36), NEWID()) + '_deleted_user@kitos.dk',
I think we should also do what the "delete command" does (in code) which covers:
- Remove all sso identities
- Remove all system roles
- Remove all contract roles
- Remove all dpr roles
- Remove all org unit roles

2022-10-06 13:09 UTC, a-naskret commented
@mrjsawdk ready for review

2022-10-07 05:50 UTC, mrjsawdk approved these changes

2022-10-07 05:50 UTC, mrjsawdk commented on Infrastructure.DataAccess/Migrations/SQLScripts/Migrate_Users_Not_Associated_With_Any_Org.sql
> +	WHERE T1.Id IS NULL AND T0.Deleted = 0
do not delete global admins

2022-10-07 05:50 UTC, mrjsawdk commented on Infrastructure.DataAccess/Migrations/SQLScripts/Migrate_Users_Not_Associated_With_Any_Org.sql
> +	WHERE T1.Id IS NULL AND T0.Deleted = 0
i fixed that

2022-10-07 05:54 UTC, mrjsawdk approved these changes

2022-10-07 06:19 UTC, merged