Feature/KITOSUDV-3294
Strongminds/kitos pull request #822
Opened 2022-10-06 13:06 UTC by a-naskret

## KITOS Pull request template
The following procedure dictates the steps needed before a Pull request can be merged into master.

- [ ] **Implement**: 
      *All requirements are implemented and unit tests are green*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*
      
- [ ] **Request review**: 
      *Tag whomever you wish to review your code*
      
- [ ] **Review completed**: 
      *Reviewer ticks this box when review comments have been submitted*
      
- [ ] **Changes**: 
      *PR owner and reviewer agrees on which changes must be made and the changes are committed.*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*

2022-10-06 13:08 UTC, a-naskret commented on Presentation.Web/app/components/it-contract/tabs/it-contract-tab-main.view.html
>                              <single-select-select2 id="criticality"
I wanted to add the help text to the directive (like to the select2Option), but the label is defined in the view so I had to add the help text here. I guess to add the help text to the directive we would also have to move the label there

2022-10-07 06:15 UTC, mrjsawdk requested changes
@a-naskret It has been misunderstood. I made a better description on the story

2022-10-07 12:17 UTC, mrjsawdk approved these changes
@a-naskret One final change... test it and it should be good 2 merge

2022-10-07 12:17 UTC, mrjsawdk commented on Presentation.Web/app/shared/singleSelect/singleSelectSelect2.directive.ts
> +                            scope.optionDescription = value.optionalObjectContext.description;
if there is no Optional object context then this will fail

Use null propagation `value.optionalObjectContext?description`

2022-10-07 12:17 UTC, mrjsawdk commented on Presentation.Web/app/shared/singleSelect/singleSelectSelect2.directive.ts
> +                            scope.optionDescription = value.optionalObjectContext.description;
actually it could all be rewritten into a single statement:
`scope.optionDescription = value?.optionalObjectContext?.description;`

2022-10-07 12:17 UTC, mrjsawdk commented on Presentation.Web/app/shared/singleSelect/singleSelectSelect2.directive.ts
> +                            scope.optionDescription = value.optionalObjectContext.description;
so no if/else

2022-10-07 12:44 UTC, merged