Feature/KITOSUDV-3317-backend
Strongminds/kitos pull request #848
Opened 2022-11-18 10:06 UTC by a-naskret

## KITOS Pull request template
The following procedure dictates the steps needed before a Pull request can be merged into master.

- [ ] **Implement**: 
      *All requirements are implemented and unit tests are green*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*
      
- [ ] **Request review**: 
      *Tag whomever you wish to review your code*
      
- [ ] **Review completed**: 
      *Reviewer ticks this box when review comments have been submitted*
      
- [ ] **Changes**: 
      *PR owner and reviewer agrees on which changes must be made and the changes are committed.*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*

2022-11-21 14:20 UTC, a-naskret commented
ready if green on integration

2022-11-22 07:17 UTC, mrjsawdk requested changes
@a-naskret some changes

2022-11-22 07:17 UTC, mrjsawdk commented on Infrastructure.DataAccess/Migrations/202211211413155_AddedStsOrganizationChangeLog.cs
> +                .PrimaryKey(t => t.Id)
should be removed and redone with changes to model

2022-11-22 07:17 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/V1/Mapping/StsOrganizationChangeLogOriginMappingExtensions.cs
> +        public static StsOrganizationChangeLogOrigin ToStsOrganizationChangeLogOrigin(this StsOrganizationChangeLogOriginOption value)
why maintain an unused method?

2022-11-22 07:17 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/V1/StsOrganizationSynchronizationController.cs
> +        [Route("changelog/{numberOfLastChangeLogs}")]
route should be `connection/change-log`
the "query" should be... a query parameter, not a resource id

name should be `numberOfChangeLogs`

2022-11-22 07:17 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/V1/StsOrganizationSynchronizationController.cs
> +        private static IEnumerable<StsOrganizationChangeLogResponseDTO> MapChangeLogResponseDtoIEnumerable(IEnumerable<StsOrganizationChangeLog> logs)
read that name and tell me it is a good name :-)

2022-11-22 07:17 UTC, mrjsawdk commented on Presentation.Web/Controllers/API/V1/StsOrganizationSynchronizationController.cs
> +            return logs.ToList().Select(MapConsequenceToDto).ToList();
why tolist twice... is it not enough to do it in the end?

2022-11-22 07:17 UTC, mrjsawdk commented on Presentation.Web/Models/API/V1/Organizations/StsOrganizationChangeLogResponseDTO.cs
> +        public string? Name { get; set; }
why add nullable to the string?... it is a reference type and already nullable. We did not enable nullable compiler checks and that's what the "?" is for in C# - no runtime behavior changes

2022-11-22 07:17 UTC, mrjsawdk commented on Presentation.Web/Models/API/V1/Organizations/StsOrganizationChangeLogResponseDTO.cs
> +        public string? Name { get; set; }
Once migrated to a user you chan change it to a UserWithEmailDTO

2022-11-22 07:17 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Organizations/StsOrganizationSynchronizationApiTest.cs
> +            using var logsResponse = await SendGetLogsAsync(targetOrgUuid, 5, cookie);
only this line is part of the ACT... the other two are prerequisites thereby making them part of the "arrange"

2022-11-22 07:17 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Organizations/StsOrganizationSynchronizationApiTest.cs
> +            using var logsResponse = await SendGetLogsAsync(targetOrgUuid, 5, cookie);
same comment as for the first test.. - the same goes for the rest

2022-11-22 07:17 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Organizations/StsOrganizationSynchronizationApiTest.cs
> +            var targetOrgUuid = await CreateOrgWithCvr(AuthorizedCvr);
We are adding a lot of small unit-test-like tests here..


think we need to combine the different cases into one test, so we limit the amount of slow calls...

2022-11-22 07:17 UTC, mrjsawdk commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/Organizations/StsOrganizationSynchronizationServiceTest.cs
> +        public void GetChangeLogForOrganization_GetOrganization_Returns_OperationError()
GetChangeLogForOrganization_GetOrganization_Returns_OperationError
--- that name is so very generic... be more precise as to the why and the what

2022-11-22 07:17 UTC, mrjsawdk commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/Organizations/StsOrganizationSynchronizationServiceTest.cs
> +        public void GetChangeLogForOrganization_Returns_All_Logs()
use theory in stead of making two identical tests

2022-11-22 07:17 UTC, mrjsawdk commented on Tests.Unit.Core.ApplicationServices/ApplicationServices/Organizations/StsOrganizationSynchronizationServiceTest.cs
> +                Connected = true,
what about the test that proves that the logs are written when an update is performed?

2022-11-22 07:17 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +                        var error = LogChanges(organization.StsOrganizationConnection, consequences);
should also be called in the "CreateConnection" scenario. 
In that case you can provide the consequences in the app service by extracting all fk org units and setting them as "added" in the consequences ctor...
You can use `organization.GetRoot().Flatten().Where(x=>x.origin==....)` to get the fk org units

2022-11-23 11:54 UTC, mrjsawdk requested changes
only a partial review before I go to a meeting

2022-11-23 11:54 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/IStsOrganizationSynchronizationService.cs
> +        IEnumerable<StsOrganizationConsequenceLog> ConvertConsequencesToConsequenceLogs(OrganizationTreeUpdateConsequences consequences);
no no why is this on the service???? it's an extension method thing...

2022-11-23 11:54 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Organizations/StsOrganizationSynchronizationApiTest.cs
> +        public async Task Can_GET_LOGS_With_Addition_Consequences()
naming... this is not just addition rights?

2022-11-23 11:54 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +                                        if (importLogResult.AddedChangeLogs.Contains(removedLog))
what is the purpose of this???? seems like logic mess

2022-11-23 11:54 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +                return new OperationError("Number of change logs to get cannot be lower than 0", OperationFailure.BadInput);
error message and constraint disagree

2022-11-23 11:54 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +            return new StsOrganizationConnectionImportLogResult(newLogs, logsToRemove);
you are combining newLogs which is from a different use case with something related to the removal case.. return type is messy

2022-11-23 11:57 UTC, a-naskret commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +        public StsOrganizationConnectionImportLogResult AddNewLogs(IEnumerable<StsOrganizationChangeLog> newLogs)
wierd result type

2022-11-27 08:37 UTC, mrjsawdk requested changes

2022-11-27 08:37 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +                _stsChangeLogRepository.RemoveRange(disconnectionResult.RemovedChangeLogs);
remember to check of there are any before calling remove range

2022-11-27 08:37 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +                    {
Adding this cleanup (saving a match)

```
  return Modify(organizationId, organization =>
                LoadOrganizationUnits(organization)
                    .Bind(importRoot => organization.UpdateConnectionToExternalOrganizationHierarchy(OrganizationUnitOrigin.STS_Organisation, importRoot, levelsToInclude, subscribeToUpdates))
                    .Select(consequences =>
                    {
                        if (consequences.DeletedExternalUnitsBeingDeleted.Any())
                        {
                            _organizationUnitRepository.RemoveRange(consequences.DeletedExternalUnitsBeingDeleted.Select(x => x.organizationUnit).ToList());
                        }
                        foreach (var (affectedUnit, _, _) in consequences.OrganizationUnitsBeingRenamed)
                        {
                            _domainEvents.Raise(new EntityUpdatedEvent<OrganizationUnit>(affectedUnit));
                        }
                        return consequences;
                    })
                    .Bind(WithLogEntries)
                    .Bind(logEntries => organization.AddExternalImportLog(OrganizationUnitOrigin.STS_Organisation, logEntries))
                    .Match(importLogResult =>
                    {
                        if (importLogResult.RemovedChangeLogs.Any())
                        {
                            _stsChangeLogRepository.RemoveRange(importLogResult.RemovedChangeLogs);
                        }

                        return Maybe<OperationError>.None;
                    }, error => error)
            );
```

2022-11-27 08:37 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +            changeLog.LogTime = DateTime.Now;
inject IOperation clock and get the time from that

2022-11-27 08:37 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +                if (user == null)
why are you checking an injected fact... the active user context is the authenticated user... if you don't trust that then you would need this check in every method in kitos dealing with auth (all methods almost)

Trust the id

2022-11-27 08:37 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +                if (user == null)
I am adding afix in the PR for this

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Extensions/ExternalOrganizationUnitExtensions.cs
> +        /// TODO:
fix the todo

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Extensions/ExternalOrganizationUnitExtensions.cs
> +        /// TODO:
fix the todo

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/Organization.cs
> +            return GetStsOrganizationConnection(origin)
![image](https://user-images.githubusercontent.com/13116889/204125401-e4eb7c1f-ede5-49d9-b6d4-b08f25902173.png)

@a-naskret Remind me of this entry in our talk as it is the design thing we will talk about

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/Organization.cs
> +                .Bind<OrganizationTreeUpdateConsequences>(connection =>
you have the connection in your parameter yet you still access the property. Had you extracted an abstraction you would have called the param and that would actually improve the design.. also a good place to visit in our talk

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/Organization.cs
> +                        StsOrganizationConnection.SynchronizationDepth =
here the specific field is also being called even if the param is used in the beginning..

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/Organization.cs
> +                .Bind<StsOrganizationConnectionAddNewLogsResult>(connection => connection.AddNewLogs(changeLogToAdd.WrapAsEnumerable()));
why is the log as itself added as an enumereble?,,, a log entry is a single thing right?

It then has a collection of consequences inside

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/Organization.cs
> +        private Result<StsOrganizationConnection, OperationError> GetStsOrganizationConnection(OrganizationUnitOrigin origin)
The interface we needed here was a IExternalConnection or something like that if the purpose is to handle an origin agnostic connection interface

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationChangelog.cs
> +        public virtual StsOrganizationConnection StsOrganizationConnection { get; set; }
remember a default ctor setting the value of the collections (easier to code against than a possible.null)

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationChangelog.cs
> +    public class StsOrganizationChangeLog: Entity
again something specific for the generic stuff

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +        public StsOrganizationConnectionAddNewLogsResult AddNewLogs(IEnumerable<StsOrganizationChangeLog> newLogs)
why is it a list in the param????


that just intoduces more issues that you should, but don't take into account such as
- Guarding for duplicates within the list

Also, you are missin to check for addition of the same log twice.. You can use "contains" for that...
You should also throw ArgumentNullException if the arg is null
Change from list arg ti single object arg

2022-11-27 08:37 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +                return new OperationError("Number of change logs to get cannot be lower than 0", OperationFailure.BadState);
again... this error message disagrees with the parameter check... it MUST be above zero, not just "not lower than 0)

2022-11-27 08:37 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Organizations/StsOrganizationSynchronizationApiTest.cs
> +            using var relocationConsequencesResponse = await SendGetUpdateConsequencesAsync(targetOrgUuid, firstRequestLevels, cookie);
Ok so let's take this again... the point of consolidating this method into one was not to just copy all of the tests into one.. it was to save slow, external calls so let's me be more precise:
- Make a setup do the amount of slow imports that you need. I see 3 update calls, but in order to deal with a collection "more than one" should be ok. See if you can squeeze the test down to two updates, thereby saving 
- A call to GetConsequences
- A call to PUT

That at least saves us some time there

2022-11-27 08:37 UTC, mrjsawdk commented on Tests.Integration.Presentation.Web/Organizations/StsOrganizationSynchronizationApiTest.cs
> +            foreach (var consequence in consequences)
when you assert two collections, the first thing to check is if they are of equal size... That stops it before getting to deep into the assertion that would just fail in Assert.NotNull

Also, this current implementation does not catch of the logs collection is larger than the consequences (expected)

2022-11-29 10:08 UTC, a-naskret commented on Tests.Integration.Presentation.Web/Organizations/StsOrganizationSynchronizationApiTest.cs
> +            //Arrange
@mrjsawdk this is the flaky (or used to be flaky) test we talked about

2022-11-29 12:40 UTC, mrjsawdk requested changes

2022-11-29 12:40 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +            var newLogEntries = newLogInput.Entries.Select(x =>
Is it valid to add a log if not connected?

2022-11-29 12:40 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +            if (number <= 0)
is this call valid if not connected?

2022-11-29 12:40 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +            var newLogEntries = newLogInput.Entries.Select(x =>
hint: Return type should be `Result<ExternalConnectionAddNewLogsResult, OperationError>` and client should handle it of course

2022-11-29 12:40 UTC, mrjsawdk commented on Core.DomainModel/Organization/StsOrganizationConnection.cs
> +            var newLogEntries = newLogInput.Entries.Select(x =>
missin null check (that will be throwing an argumentnullexception)

2022-11-29 12:40 UTC, mrjsawdk commented on Core.ApplicationServices/Organizations/StsOrganizationSynchronizationService.cs
> +        private Result<StsOrganizationChangeLog, OperationError> WithLogEntries(OrganizationTreeUpdateConsequences consequences)
this return value is now only used to produce the input... that makes no sense.. clean up and remove the added extension if this class is the only one using it

2022-11-29 13:17 UTC, mrjsawdk approved these changes
@a-naskret added some more fixes. ready to merge when green.. then make sure the frontend still works with the latest revisions to the backend

2022-11-30 06:11 UTC, merged