Feature/KITOSUDV-3317-frontend
Strongminds/kitos pull request #854
Opened 2022-11-24 08:30 UTC by a-naskret

## KITOS Pull request template
The following procedure dictates the steps needed before a Pull request can be merged into master.

- [ ] **Implement**: 
      *All requirements are implemented and unit tests are green*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*
      
- [ ] **Request review**: 
      *Tag whomever you wish to review your code*
      
- [ ] **Review completed**: 
      *Reviewer ticks this box when review comments have been submitted*
      
- [ ] **Changes**: 
      *PR owner and reviewer agrees on which changes must be made and the changes are committed.*
      
- [ ] **Merge master into branch / rebase with master**: 
      *Make sure you are testing your changes and how they co-exist with the latest version of master*
      
- [ ] **Green on integration**: 
      *All integration tests are green on integration*

2022-11-24 11:50 UTC, a-naskret commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.view.html
> +                <h6>Number of updates</h6>
Text to danish

2022-11-24 11:50 UTC, a-naskret commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.view.html
> +                <h6>Update date</h6>
Text to danish

2022-11-24 11:56 UTC, a-naskret commented on Presentation.Web/app/components/local-config/import/fk-organization-import-config.view.html
> +                <span>Change log</span>
text to danish

2022-11-30 08:50 UTC, mrjsawdk requested changes
@a-naskret some input

2022-11-30 08:50 UTC, mrjsawdk commented on Core.DomainModel/Organization/IExternalConnectionChangelog.cs
> +        int Id { get; }
in stead just add a VM in  UI (extend the dto) and add the index to that... it does not need the real db id

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.component.ts
> +        static $inject: string[] = [];
do we need this array if we don't want to inject anything?

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.component.ts
> +        logTime: string;
string | null = null

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.component.ts
> +        responsibleEntityText: string;
string | null = null

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.component.ts
> +        changeLog: Models.Api.Organization.ConnectionChangeLogDTO
add the public properties here (the two others)

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.view.html
> +            <td>{{ ctrl.responsibleEntityText }}</td>
should it not be "render once" ? `{{::}}`

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.view.html
> +    <fk-orgnization-import-consequences-log consequences="ctrl.changeLog.consequences"></fk-orgnization-import-consequences-log>
no need to have both tags.. just add a closed tag:
`<fk-orgnization-import-consequences-log consequences="ctrl.changeLog.consequences" />`

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-log.view.html
> +    <fk-orgnization-import-consequences-log consequences="ctrl.changeLog.consequences"></fk-orgnization-import-consequences-log>
also use data- prefix to the consequences attr

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-logs-root.component.ts
> +            private readonly  notify) {
no need for this or the error message. Not going to help the user anyways

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-logs-root.component.ts
> +        selectedChangeLog: Models.Api.Organization.ConnectionChangeLogDTO;
remember default values for these

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-logs-root.component.ts
> +                selectedElement: this.selectedChangeLog && optionMap[this.selectedChangeLog.id],
since you are not rebiding then the selected element will always be undefined ... right?

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-logs-root.view.html
> +        <fk-organization-import-change-log change-log="changeLog"></fk-organization-import-change-log>
also rewrite to a closed tag and remember to use data- prefixes
```
<fk-organization-import-change-log data-change-log="changeLog" />
```

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-logs-root.view.html
> +    <div ng-hide="changeLog.id !== ctrl.selectedChangeLog.id">
null check if default value will be null in the new model...

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-config.view.html
> +                <span>Change log</span>
Ændringslog

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-config.view.html
> +            <fk-organization-import-change-logs-root organization-uuid="{{::ctrl.currentOrganizationUuid}}"></fk-organization-import-change-logs-root>
overly complex .. remember closed tags, simpler binding and data prefixes

```
<fk-organization-import-change-logs-root data-organization-uuid="ctrl.currentOrganizationUuid" />
```

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-config.view.html
> +            <a id="expand_collapse_registrations" class="task-fold control-label" data-ng-click="isExpanded = !isExpanded">
id must have been copy pasted from somewhere else...

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-logs-root.component.ts
> +        selectedChangeLog: Models.Api.Organization.ConnectionChangeLogDTO;
hmm... are you sure about the type? As far as I can see select2 works on select2 vms...
it's cheating with the correlated id here..

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/components/local-config/import/fk-organization-import-change-logs-root.component.ts
> +        selectChangeLogModel = {};
move default value to declaration and fix the type of it

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/helpers/connection-change-log-helper.ts
> +        static createDictionaryFromChangeLogList(changeLogs: Array<Models.Api.Organization.ConnectionChangeLogDTO>) {
please specify the type of the return value... it sure looks like a dictionary of id-> select2object ;)

2022-11-30 08:50 UTC, mrjsawdk commented on Presentation.Web/app/models/api/organization/connection-update-organization-unit-consequence-dto.ts
> +        uuid : string;
why are you adding the ";"??

2022-12-01 12:13 UTC, merged